### ISSUE TITLE
🚀 Stride Docs Release Checklist 

### ISSUE THREAD

**Issue by VaclavElias** [stride3d/stride-docs#111]
The Stride Docs staging is now running here https://stride-doc-staging.azurewebsites.net/latest/en/

Remaining tasks:

- [x] fix the JP language, even thought we will disable JP
- [x] lock specific docfx version in GitHub Action - to avoid surprises when the latest is used automatically
- [x] add missing lfs to GitHub Actions
- [x] check the search from the Stride website is going to work with new docs
- [x] test staging docs website
- [x] prepare release branch
- [x] release
- [x] test

Additional tasks:
- [x] set up wiki for Stride Docs
- [x] make fast track working

**Comment by VaclavElias** [comment]
Closing. All resolved.
